""" General settings -----------------------
set nocompatible
set title " Set title in terminal window
set number " line numbers
set ruler
set hlsearch
set ignorecase
set listchars=tab:▸\ ,eol:¬
set list
set history=1000
set mouse=nv
set cursorline
set incsearch
set ic
set nobackup
set noswapfile
set foldmethod=indent   "fold based on indent
set foldnestmax=2       "deepest fold is 2 levels
set nofoldenable        "don't fold by default
" set foldlevel=2
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

colorscheme molokai " from https://github.com/tomasr/molokai

filetype on " Enable file type detection
filetype plugin on
filetype plugin indent on

syntax on
runtime macros/matchit.vim " Make % command switch for opening/closed if-else

" Syntax of these languages is fussy over tabs Vs spaces
autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

" Customisations based on house-style (arbitrary)
autocmd FileType html setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType css setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType javascript setlocal ts=4 sts=4 sw=4 noexpandtab

autocmd BufNewFile,BufRead *.rss setfiletype xml " Treat .rss files as XML
autocmd BufNewFile,BufRead *.ftl setfiletype freemarker


""" Remaps -----------------------
" Disable arrows to move around
nnoremap <Up> <Nop>
nnoremap <Down> <Nop>
nnoremap <Left> <Nop>
nnoremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>

" Recalling commands from history
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>

nnoremap <silent> <C-l> :<C-u>nohlsearch<CR><C-l> " Set ctr-l to clean up last search match highlight

" Shortcuts for opening file in same directory as current file
cnoremap <expr> %% getcmdtype() == ':' ? escape(expand('%:h'), ' \').'/' : '%%'
cnoremap %% <C-R>=expand('%:h').'/'<cr>
map <leader>ew :e %%
map <leader>es :sp %%
map <leader>ev :vsp %%
map <leader>et :tabe %%

" Fix the & command in normal+visual modes
nnoremap & :&&<Enter>
xnoremap & :&&<Enter>

nnoremap K i<CR><Esc> " The opposite of J:

" Strip trailing whitespaces
nnoremap <silent> <F5> :call <SID>StripTrailingWhitespaces()<CR>


""" Plugin settings -----------------------
" For pathogen plugin
execute pathogen#infect()

" netrw: avoiding 'Hit enter to continue' message over scp
let g:netrw_silent=1
let g:netrw_liststyle=3

" vim-commentary:
autocmd FileType sql set commentstring=--\ %s

" syntastic: JsHint as JavaScript linter (with Node Version Manager too!)
if $PATH !~ "\.nvm"
    let $PATH="/home/services/.nvm/versions/node/v0.12.2/bin:" . $PATH
endif
nnoremap <F7> :SyntasticToggleMode<CR>
let g:syntastic_javascript_checkers = ['jshint']

" airline status bar
set laststatus=2
" let g:airline#extensions#tabline#enabled = 1
" let g:airline_theme='light'
let g:airline_powerline_fonts=1

" webdevicons: icons for file types in airline status bar
set guifont=Droid\ Sans\ Mono\ for\ Powerline\ Plus\ Nerd\ File\ Types\ 11
let g:webdevicons_enable_nerdtree = 0


""" Function definitions -----------------------
function <SID>StripTrailingWhitespaces()
    " Preparation: save last search, and cursor position.
    let _s=@/
    let l = line(".")
    let c = col(".")
    " Do the business:
    %s/\s\+$//e
    " Clean up: restore previous search history, and cursor position
    let @/=_s
    call cursor(l, c)
endfunction
