" Some Neovim defaults
set autoindent                 " Copy indent from current line when starting a new line
set autoread                   " Auto reload file if modified outside Vim
set backspace=indent,eol,start " Allow backspacing over autoindent, over line breaks (join lines) and over the start of insert
set belloff=all                " Never ring the system bell
set encoding=utf-8             " Vim defaults to latin1 or value from $LANG
set fillchars=                 " Vim defaults to 'vert:│,fold:·'
set formatoptions=tcqj         " Automation of formatting
set history=10000              " Set history length (this is the maximum possible value)
set hlsearch                   " Highlight searched strings
set incsearch                  " Start highlighting strings at every char type
set laststatus=2               "Statusline is always shown
set nocompatible               " No compatible with the old Vi
set ruler                      " Show line and column number
set showcmd                    " Show (partial) command in the last line of the screen
set sidescroll=1               " Minimum number of columns to scroll horizontally
set smarttab                   " With a <Tab> in front of a line, inserts blanks according to 'shiftwidth'
set tabpagemax=50              " Max num of tab pages to be opened by :tab all or -p
set wildmenu                   " Command line completion operates in an enhanced mode
set showmatch                  " Blink on matching brackets
set cursorline                 " Highlight current cursor line

" General
set number                 " Set line numbers
set title                  " Set title in terminal window
set clipboard+=unnamedplus " to put yanked lines into clipboard
set hidden                 " Switching to another buffer, it hides already opened and modified buffers instead of closing them
set nobackup               " Do not produce backup files with ~ postfix
set iskeyword+=\-          " Makes dashed variables like $my-variable, available for autocompletion
set updatetime=100         " If nothing happens on screen, after how many ms the swap file is written to disk (default is 4000)
filetype plugin indent on  " Detect file types, load its plugin and apply its indentation
syntax enable              " Switch on syntax highlighting

" Indentation
set smartindent   " Do smart autoindenting when starting a new line
set ignorecase    " Our search will be case insensitive by default: without this, set smartcase does not work!
set smartcase     " Our search will be case sensitive if it contains an uppercase letter
set expandtab     " When pressing <Tab> use spaces instead
set softtabstop=2 " How many spaces instead of a <Tab>
set shiftwidth=2  " How many spaces with autoindent
set tabstop=2     " Number of spaces used to visually represent a <Tab>

" Folding
set foldmethod=indent " fold based on indent
set nofoldenable      " no fold by default
set foldcolumn=2      " show columns of folding representation at a side of window
set foldlevel=1       " folds with a higher level will be closed
set foldnestmax=2     " deepest fold nesting

" Autocompletion
set omnifunc=syntaxcomplete#Complete " Omnifunc autocompletion
